BEGIN;

CREATE TABLE IF NOT EXISTS users (
  id UUID PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS friendships (
  requester_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  requestee_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  since TIMESTAMP
);

CREATE TABLE IF NOT EXISTS posts (
  id UUID PRIMARY KEY,
  author_id UUID NOT NULL REFERENCES users(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  created_at TIMESTAMP NOT NULL DEFAULT NOW()
);

COMMIT;
